'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class MyResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Lobster.Framework.MyResources", GetType(MyResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''    &apos;Name&apos;: &apos;ClassModel&apos;, 
        '''    &apos;ClassModelId&apos;: &apos;26761d27-392c-4466-ab5d-7849c7c91474&apos;, 
        '''    &apos;SetNameOverload&apos;: &apos;&apos;, 
        '''    &apos;ParentClassModelId&apos;: &apos;00000000-0000-0000-0000-000000000000&apos;, 
        '''    &apos;CompositeClassModelId&apos;: &apos;00000000-0000-0000-0000-000000000000&apos;, 
        '''    &apos;IsComposite&apos;: true, 
        '''    &apos;FieldModels&apos;: [{
        '''        &apos;DataTypeId&apos;: 10, 
        '''        &apos;Name&apos;: &apos;Name&apos;, 
        '''        &apos;ClassModelId&apos;: &apos;26761d27-392c-4466-ab5d-7849c7c91474&apos;, 
        '''        &apos;FieldModelId&apos;: &apos;5d2e961f-4313-4bec-9de6-22cdeafb5406&apos;
        '''    }, {
        '''        [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ClassModelClassModelState() As String
            Get
                Return ResourceManager.GetString("ClassModelClassModelState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''    &apos;Name&apos;: &apos;FieldModel&apos;, 
        '''    &apos;ClassModelId&apos;: &apos;c26f63b3-df37-49d6-a238-aa04009dabb1&apos;, 
        '''    &apos;SetNameOverload&apos;: &apos;&apos;, 
        '''    &apos;ParentClassModelId&apos;: &apos;26761d27-392c-4466-ab5d-7849c7c91474&apos;, 
        '''    &apos;CompositeClassModelId&apos;: &apos;26761d27-392c-4466-ab5d-7849c7c91474&apos;, 
        '''    &apos;IsComposite&apos;: false, 
        '''    &apos;FieldModels&apos;: [{
        '''        &apos;DataTypeId&apos;: 4, 
        '''        &apos;Name&apos;: &apos;DataTypeId&apos;, 
        '''        &apos;ClassModelId&apos;: &apos;c26f63b3-df37-49d6-a238-aa04009dabb1&apos;, 
        '''        &apos;FieldModelId&apos;: &apos;4785aea5-79e4-4413-9313-5c91f0dfb93a&apos;
        '''    }, {
        '''  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property FieldModelClassModelState() As String
            Get
                Return ResourceManager.GetString("FieldModelClassModelState", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
